spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://172.17.0.5:9411/
  application:
    name: toures-balon-producto-ciudad
  data:
    mongodb:
      uri:  mongodb://172.17.0.9/touresbalon-producto-ciudad
      port: 27017
      password:
      username: 
server:
    port: 0
eureka:
    client:
        serviceUrl:
            defaultZone: http://172.17.0.3:8761/eureka
    instance:
        prefer-ip-address: true
