spring:
    cloud:
        gateway:
            routes:
            - id: toures-balon-usuario
              uri: http://172.17.0.6:9091
              predicates:
              - Path=/usuario/**
              filters:
              - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.4:8761/eureka
