spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.0.92:9411/
  application:
    name: toures-balon-configuracion
  redis:
    host: 192.168.0.92
  profiles:
    active: prod
server:
  port: 8080
