spring:
    cloud:
        loadbalancer:
            ribbon:
                enable: false
        gateway:
            discobery:
                locator:
                    lower-case-service-id: true
                    enabled: true
            routes:
            - id: toures-balon-usuario-routes
              uri: lb://toures-balon-usuario
              predicates:
              - Path=/usuario/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.4:8761/eureka
