server:
  port: 8080
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.0.92:9411/
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://192.168.0.92:3306/toures_domain_usuario?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: gemadb
    password: m22102013M..
    initialization-mode: always
    platform: mysql
  application:
    name: toures-balon-usuario
gema:
  kafka:
    producer:
      enabled: true
      bootstrap-server: htpp://192.168.0.92:29092
    consumer:
      enabled: true
      bootstrap-server: htpp://192.168.0.92:29092
      
dividing-factor: 1000
