server:
  port: 0
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.0.6:9411/
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/toures_domain_usuario
    username: root
    password: m22102013M..
  application:
    name: toures-balon-usuario
eureka:
  client:
    serviceUrl:
      defaultZone: "http://192.168.0.6:8761/eureka"
  instance:
    prefer-ip-address: true
