
server:
  port: 8080
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.0.92:9411/
  application:
    name: toures-balon-oauth
gema:
  oauth:
    application-config:
      frontAngular:
        password: pica2020..
        name: angular
        jwt-password: droptable2020..
        time-expiration: 360000
