spring:
    sleuth:
     sampler:
      probability: 1.0
    zipkin:
     base-url: http://192.168.0.92:9411/
    cloud:
         gateway:
            discovery:
              locator:
                enabled: true
                lower-case-service-id: true
            globalcors:
                corsConfigurations:
                  '[/**]':
                    allowedOrigins: "*"
                    allowed-methods:
                    - "*"
                    allowed-headers:
                    - "*"
                    allow-credentials: true

            routes:
            - id: toures-balon-usuario
              uri: lb://toures-balon-usuario-service
              predicates:
              - Path=/usuario/**
            - id: toures-balon-producto-hospedaje
              uri: lb://TOURES-BALON-PRODUCTO-HOSPEDAJE #http://172.17.0.6:9091
              predicates:
              - Path=/producto/hospedaje/**
            - id: toures-balon-oauth
              uri: lb://toures-balon-oauth-service
              predicates:
              - Path=/oauth/**
            - id: touresbalon-producto-evento
              uri: lb://TOURESBALON-PRODUCTO-EVENTO
              predicates:
              - Path=/producto/evento/**  
            - id: touresbalon-producto-transporte
              uri: lb://TOURESBALON-PRODUCTO-TRANSPORTE
              predicates:
              - Path=/producto/transporte/**
            - id: touresbalon-proveedor-hospedaje
              uri: lb://TOURESBALON-PROVEEDOR-HOSPEDAJE
              predicates:
              - Path=/proveedor/hospedaje,/proveedor/hospedaje/plantilla-consulta,/proveedor/hospedaje/auth
            - id: touresbalon-proveedor-hospedaje-disponibilidad
              uri: lb://TOURESBALON-PROVEEDOR-HOSPEDAJE-DISPONIBILIDAD
              predicates:
              - Path=/proveedor/hospedaje/disponibilidad/**
            - id: touresbalon-proveedor-vuelo
              uri: lb://TOURESBALON-PROVEEDOR-VUELO
              predicates:
              - Path=/proveedor/vuelo,/proveedor/vuelo/plantilla-consulta,/proveedor/vuelo/auth
            - id: touresbalon-proveedor-vuelo-disponibilidad
              uri: lb://TOURESBALON-PROVEEDOR-VUELO-DISPONIBILIDAD
              predicates:
              - Path=/proveedor/vuelo/disponibilidad/**  
            - id: touresbalon-proveedor-evento
              uri: lb://TOURESBALON-PROVEEDOR-EVENTO
              predicates:
              - Path=/proveedor/evento,/proveedor/evento/plantilla-consulta,/proveedor/evento/auth
            - id: touresbalon-proveedor-evento-disponibilidad
              uri: lb://TOURESBALON-PROVEEDOR-EVENTO-DISPONIBILIDAD
              predicates:
              - Path=/proveedor/evento/disponibilidad/**  
            - id: touresbalon-proveedor-terrestre
              uri: lb://TOURESBALON-PROVEEDOR-TERRESTRE
              predicates:
              - Path=/proveedor/terrestre,/proveedor/terrestre/plantilla-consulta,/proveedor/terrestre/auth
            - id: touresbalon-proveedor-terrestre-disponibilidad
              uri: lb://TOURESBALON-PROVEEDOR-TERRESTRE-DISPONIBILIDAD
              predicates:
              - Path=/proveedor/terrestre/disponibilidad/**  
            - id: toures-balon-configuracion
              uri: lb://toures-balon-configuracion-service
              predicates:
              - Path=/configuracion/**
            - id: toures-balon-carro
              uri: lb://TOURES-BALON-CARRO
              predicates:
              - Path=/carro/**  
            - id: toures-balon-campana
              uri: lb://toures-balon-campana-service
              predicates:
              - Path=/campana/**  
            - id: toures-balon-orden
              uri: lb://toures-balon-orden-service
              predicates:
              - Path=/orden/**  
            - id: toures-balon-usuario-categoria
              uri: lb://toures-balon-usuario-categoria-service
              predicates:
              - Path=/categoria/**,/categoria/beneficio/**,/categoria/transaccion/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.6:8761/eureka
  instance:
    prefer-ip-address: true
oauth:
  enabled: true
  jwt:
    issuer: angular
    password: droptable2020..
    exclude-matchers:
    - method: POST
      paths:
      - /oauth/token
      - /usuario
      - \/configuracion.*
      - \/carro.*
      - \/campana.*
      - \/orden.*
      - \/categoria.*
      - \/beneficio.*
      - \/transaccion.*
      - \/usuario.*
    - method: GET
      paths:
      - \/configuracion.*
      - \/carro.*
      - \/campana.*
      - \/proveedor.*
      - \/orden.*
      - \/categoria.*
      - \/beneficio.*
      - \/transaccion.*
      - \/testkubernetes.*
      - \/usuario.*
    - method: PUT
      paths:
      - \/configuracion.*
      - \/proveedor.*
      - \/categoria.*
      - \/beneficio.*
      - \/transaccion.*
    - method: DELETE
      paths:
      - \/configuracion.*
      - \/carro.*
      - \/categoria.*
      - \/beneficio.*
      - \/transaccion.*
    matchers-with-role:
    - method: GET
      paths:
      - \/producto.*
      roles:
        - ROLE_ADMIN
    - method: POST
      paths:
      - \/usuario.*
      - \/producto.*
      roles:
        - ROLE_ADMIN
