spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.0.92:9411/
  application:
    name: touresbalon-proveedor-evento-disponibilidad
server:
  port: 8080
        
resilience4j:
    circuitbreaker:
        configs:
            default:
                registerHealthIndicator: true
                slidingWindowSize: 10
                minimumNumberOfCalls: 5
                permittedNumberOfCallsInHalfOpenState: 10
                waitDurationInOpenState: 3s
                failureRateThreshold: 50
                eventConsumerBufferSize: 10
                recordExceptions:
                    - org.springframework.web.client.HttpServerErrorException
                    - java.util.concurrent.TimeoutException
                    - java.io.IOException
                    - retrofit2.HttpException
                    - java.net.SocketTimeoutException
                    - java.net.UnknownHostException
                ignoreExceptions:
