spring:
    cloud:
        gateway:
            routes:
            - id: toures-balon-usuario
              uri: lb://TOURES-BALON-USUARIO #http://172.17.0.6:9091
              predicates:
              - Path=/usuario/**
            - id: toures-balon-proveedor
              uri: lb://TOURES-BALON-PROVEEDOR #http://172.17.0.6:9091
              predicates:
              - Path=/proveedor/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.4:8761/eureka
  instance:
    prefer-ip-address: true
