
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.0.92:9411/
  application:
    name: touresbalon-producto-evento
  data:
    mongodb:
      uri:  mongodb://192.168.0.92/touresbalon-producto-evento
      port: 27017
      password:
      username: 
server:
  port: 8080
