spring:
    sleuth:
     sampler:
      probability: 1.0
    zipkin:
     base-url: http://172.17.0.11:9411/
    cloud:
        gateway:
            routes:
            - id: toures-balon-usuario
              uri: lb://TOURES-BALON-USUARIO #http://172.17.0.6:9091
              predicates:
              - Path=/usuario/**
            - id: toures-balon-proveedor
              uri: lb://TOURES-BALON-PROVEEDOR #http://172.17.0.6:9091
              predicates:
              - Path=/proveedor/**
            - id: toures-balon-producto-hospedaje
              uri: lb://TOURES-BALON-PRODUCTO-HOSPEDAJE #http://172.17.0.6:9091
              predicates:
              - Path=/producto/hospedaje/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.4:8761/eureka
  instance:
    prefer-ip-address: true
oauth:
  enabled: true
  jwt:
    issuer: angular
    password: 123456789
    exclude-matchers:
    - method: POST
      paths:
      - /oauth/token
    matchers-with-role:
    - method: GET
      paths:
      - \/usuario.*
      roles:
        - ROLE_ADMIN
    - method: POST
      paths:
      - \/usuario.*
      roles:
        - ROLE_ADMIN
