spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.0.6:9411/
  application:
    name: touresbalon-proveedor-vuelo
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: touresbalon-proveedor-vuelo
server:
  port: 0
eureka:
  client:
  #  service-url: {"http://toures-balon-discovery:8761/eureka"}
    serviceUrl:
      defaultZone: "http://192.168.0.6:8761/eureka"
  instance:
    prefer-ip-address: true
