server:
  port: 8676
---
spring:
  minio:
    url: http://192.168.0.6:9000
    bucket: toures-balon
    access-key: minioadmin
    secret-key: minioadmin
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB
  profiles:
    active: dev
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.0.6:9411/
eureka:
  client:
    serviceUrl:
      defaultZone: "http://192.168.0.6:8761/eureka"
    instance:
      prefer-ip-address: true

