spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.0.92:9411/
  application:
    name: touresbalon-proveedor-vuelo
  data:
    mongodb:
      host: 192.168.0.92
      port: 27017
      database: touresbalon-proveedor-vuelo
server:
  port: 8080
