spring:
    sleuth:
     sampler:
      probability: 1.0
    zipkin:
     base-url: http://172.17.0.11:9411/
    cloud:
        gateway:
            routes:
            - id: toures-balon-usuario
              uri: lb://TOURES-BALON-USUARIO #http://172.17.0.6:9091
              predicates:
              - Path=/usuario/**
            - id: toures-balon-proveedor
              uri: lb://TOURES-BALON-PROVEEDOR #http://172.17.0.6:9091
              predicates:
              - Path=/proveedor/**
            - id: toures-balon-producto-hospedaje
              uri: lb://TOURES-BALON-PRODUCTO-HOSPEDAJE #http://172.17.0.6:9091
              predicates:
              - Path=/producto/hospedaje/**
            - id: toures-balon-oauth
              uri: lb://TOURES-BALON-OAUTH
              predicates:
              - Path=/oauth/**
            - id: toures-balon-producto-ciudad
              uri: lb://TOURES-BALON-PRODUCTO-CIUDAD
              predicates:
              - Path=/producto/ciudad/**
            - id: touresbalon-producto-evento
              uri: lb://TOURESBALON-PRODUCTO-EVENTO
              predicates:
              - Path=/producto/evento/**  
            - id: touresbalon-producto-transporte
              uri: lb://TOURESBALON-PRODUCTO-TRANSPORTE
              predicates:
              - Path=/producto/transporte/**
            - id: touresbalon-proveedor-hospedaje
              uri: lb://TOURESBALON-PROVEEDOR-HOSPEDAJE
              predicates:
              - Path=/proveedor/hospedaje/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.9:8761/eureka
  instance:
    prefer-ip-address: true
oauth:
  enabled: true
  jwt:
    issuer: angular
    password: droptable2020..
    exclude-matchers:
    - method: POST
      paths:
      - /oauth/token
      - /usuario
    matchers-with-role:
    - method: GET
      paths:
      - \/usuario.*
      - \/producto.*
      roles:
        - ROLE_ADMIN
    - method: POST
      paths:
      - \/usuario.*
      - \/producto.*
      roles:
        - ROLE_ADMIN
